# Generated by Django 4.0.4 on 2022-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_job', models.CharField(max_length=11)),
                ('url_job', models.CharField(max_length=100)),
                ('title_job', models.CharField(max_length=100)),
            ],
        ),
    ]
