# Generated by Django 4.0.4 on 2022-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjob', '0002_jobs_description_job_jobs_how_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
